stages:
  - docker-build


### Build Docker Container ###
docker-build:
  stage: docker-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "Start building Docker Image for App"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >- 
      /kaniko/executor --insecure --insecure-registry adesso-cis1-ba-lm-dev01.test-server.ag:4567 
      --skip-tls-verify 
      --context $CI_PROJECT_DIR/ 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG 
      --verbosity debug
    - echo "Docker Image built sucessfully"
