# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
    - feature/buildpipeline
  tags:
    include:
    - '*'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '93576322-1d48-487d-907a-b18348168f79'
  imageRepository: 'aero-cad-service'
  containerRegistry: 'crda3dalusdev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/Dockerfile.client.amd64.dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
          tags: |
            latest
        ${{ else }}:
          tags: |
            latest
            $(Build.SourceBranchName)
