FROM continuumio/miniconda3:latest

RUN conda install -yc dlr-sc tigl3
RUN conda install -c conda-forge pythreejs

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

ENTRYPOINT [ "/bin/bash"]
