services:
  cq-client:
    image: szymanski2adesso/cadquery-env:2.4.0
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/Dockerfile.client.arm64.dockerfile
      cache_from:
        - szymanski2adesso/cadquery-client:2.4.0
    container_name: cq-client
    volumes:
      - ./:/home/cadquery/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    entrypoint: "/opt/anaconda/envs/cq/bin/python"
    tty: true
    ports:
      - 8085:8000
    environment:
      DISPLAY: "host.docker.internal:0"
    #network_mode: host

  cq-win_client:
    platform: linux/amd64
    build:
      context: ./docker
      dockerfile: docker/Dockerfile.jupyter.amd64.dockerfile
    container_name: cq-win-client
    volumes:
      - ./:/home/cadquery/workspace
    stdin_open: true
    entrypoint: "/opt/conda/envs/cq/bin/python"
    tty: true

  cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    container_name: cq-server
    command: "run"
    ports:
      - "5050:5000"

  cq-runtime:
    image: szymanski2adesso/cadquery-runtime:2.4.0
    platform: linux/arm64
    container_name: cq-runtime
    volumes:
      - ./:/home/cadquery/workspace
    stdin_open: true
    entrypoint: "/venv/bin/python"
    tty: true

  cq-jupyter:
    image: szymanski2adesso/cadquery-jupyter:2.4.0
    platform: linux/amd64
    container_name: cq-jupyter
    build:
      context: docker
      dockerfile: Dockerfile.jupyter.arm64.dockerfile
      cache_from:
        - szymanski2adesso/cadquery-client:2.4.0
    ports:
      - 8888:8888
    volumes:
      - ./:/home/cq/data

  cq-win-jupyter:
    platform: linux/amd64
    container_name: cq-win-jupyter
    build:
      context: docker
      dockerfile: Dockerfile.jupyter.amd64.dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./:/home/cq/data

  aero-cad-service:
    image: szymanski2adesso/cadquery-client:2.4.0
    platform: linux/arm64
    build:
      context: ./docker
      dockerfile: Dockerfile.client.arm64.dockerfile
      cache_from:
        - szymanski2adesso/cadquery-client:2.4.0
    container_name: aero-cad-service
    volumes:
      - ./:/home/cq/app
    stdin_open: true
    entrypoint: "/tmp/run.sh --s nope"
    tty: true
    ports:
      - 8086:8000
