services:
  aero-cad-service:
    image: cad-modelling-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - cad-modelling-service:latest
    container_name: aero-cad-service
    environment:
      - BROWSER_PATH=/usr/bin/chromium
      - OCP_VSCODE_HOST="host.docker.internal"
      - OCP_VSCODE_PORT=3939
      - DISPLAY_CONSTRUCTION_STEP=TRUE
    ports:
      - 8086:8000
    restart: unless-stopped
