services:
  aero-cad-service:
    image: cad-modelling-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - cad-modelling-service:latest
    container_name: aero-cad-service
    environment:
      - BROWSER_PATH=/usr/bin/chromium
    ports:
      - 8086:8000
    restart: unless-stopped
