"""add tessellation_cache table

Revision ID: 04b8c856eab9
Revises: 94e41782f22d
Create Date: 2026-04-12 21:21:39.927179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b8c856eab9'
down_revision: Union[str, None] = '94e41782f22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tessellation_cache',
    sa.Column('aeroplane_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('geometry_hash', sa.String(), nullable=False),
    sa.Column('tessellation_json', sa.JSON(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tessellation_cache_aeroplane_id'), 'tessellation_cache', ['aeroplane_id'], unique=False)
    op.create_index(op.f('ix_tessellation_cache_id'), 'tessellation_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tessellation_cache_id'), table_name='tessellation_cache')
    op.drop_index(op.f('ix_tessellation_cache_aeroplane_id'), table_name='tessellation_cache')
    op.drop_table('tessellation_cache')
    # ### end Alembic commands ###
