"""added operating_point and operating_point_set

Revision ID: 1294198940a9
Revises: d89e43f1f4ef
Create Date: 2025-05-29 18:17:30.959698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1294198940a9'
down_revision: Union[str, None] = 'd89e43f1f4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('q', sa.Float(), nullable=False),
    sa.Column('r', sa.Float(), nullable=False),
    sa.Column('xyz_ref', sa.JSON(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operating_pointsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('operating_points', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operating_pointsets')
    op.drop_table('operating_points')
    # ### end Alembic commands ###
