"""gh-821 airfoil low-Re polar and geometry

Revision ID: 16cbb884a838
Revises: c3a5992b6f25
Create Date: 2026-06-04 10:38:43.336032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cbb884a838'
down_revision: Union[str, None] = 'c3a5992b6f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airfoil_geometry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airfoil_name', sa.String(), nullable=False),
    sa.Column('max_thickness_pct', sa.Float(), nullable=False),
    sa.Column('max_camber_pct', sa.Float(), nullable=False),
    sa.Column('camber_at_te', sa.Float(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['airfoil_name'], ['airfoils.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airfoil_geometry_airfoil_name'), 'airfoil_geometry', ['airfoil_name'], unique=True)
    op.create_index(op.f('ix_airfoil_geometry_id'), 'airfoil_geometry', ['id'], unique=False)
    op.create_table('airfoil_low_re_polar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airfoil_name', sa.String(), nullable=False),
    sa.Column('reynolds', sa.Float(), nullable=False),
    sa.Column('ld_max', sa.Float(), nullable=True),
    sa.Column('cl_max', sa.Float(), nullable=True),
    sa.Column('alpha_attached_lo', sa.Float(), nullable=True),
    sa.Column('alpha_attached_hi', sa.Float(), nullable=True),
    sa.Column('drag_bucket_width', sa.Float(), nullable=True),
    sa.Column('cd_min', sa.Float(), nullable=True),
    sa.Column('stall_gentleness', sa.Float(), nullable=True),
    sa.Column('cd0', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('cl0', sa.Float(), nullable=True),
    sa.Column('cl_valid_lo', sa.Float(), nullable=True),
    sa.Column('cl_valid_hi', sa.Float(), nullable=True),
    sa.Column('min_analysis_confidence', sa.Float(), nullable=True),
    sa.Column('neuralfoil_model_size', sa.String(), nullable=False),
    sa.Column('n_crit', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['airfoil_name'], ['airfoils.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airfoil_name', 'reynolds', name='uq_airfoil_low_re_polar')
    )
    op.create_index(op.f('ix_airfoil_low_re_polar_airfoil_name'), 'airfoil_low_re_polar', ['airfoil_name'], unique=False)
    op.create_index(op.f('ix_airfoil_low_re_polar_id'), 'airfoil_low_re_polar', ['id'], unique=False)
    op.create_index(op.f('ix_airfoil_low_re_polar_reynolds'), 'airfoil_low_re_polar', ['reynolds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airfoil_low_re_polar_reynolds'), table_name='airfoil_low_re_polar')
    op.drop_index(op.f('ix_airfoil_low_re_polar_id'), table_name='airfoil_low_re_polar')
    op.drop_index(op.f('ix_airfoil_low_re_polar_airfoil_name'), table_name='airfoil_low_re_polar')
    op.drop_table('airfoil_low_re_polar')
    op.drop_index(op.f('ix_airfoil_geometry_id'), table_name='airfoil_geometry')
    op.drop_index(op.f('ix_airfoil_geometry_airfoil_name'), table_name='airfoil_geometry')
    op.drop_table('airfoil_geometry')
    # ### end Alembic commands ###
