"""added total_mass attribute to aeroplane

Revision ID: 2f80f5c2b22f
Revises: 83493febb34a
Create Date: 2025-05-26 21:46:08.617354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f80f5c2b22f'
down_revision: Union[str, None] = '83493febb34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aeroplanes', sa.Column('total_mass', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aeroplanes', 'total_mass')
    # ### end Alembic commands ###
