"""add mission_objectives and weight_items tables

Revision ID: 5b41e8c65a14
Revises: c19d4f2e7c34
Create Date: 2026-04-12 06:40:15.578961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b41e8c65a14'
down_revision: Union[str, None] = 'c19d4f2e7c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_objectives',
    sa.Column('aeroplane_id', sa.Integer(), nullable=False),
    sa.Column('payload_kg', sa.Float(), nullable=True),
    sa.Column('target_flight_time_min', sa.Float(), nullable=True),
    sa.Column('maneuverability_class', sa.String(), nullable=True),
    sa.Column('size_envelope_length_mm', sa.Float(), nullable=True),
    sa.Column('size_envelope_width_mm', sa.Float(), nullable=True),
    sa.Column('size_envelope_height_mm', sa.Float(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('target_stall_speed_ms', sa.Float(), nullable=True),
    sa.Column('target_cruise_speed_ms', sa.Float(), nullable=True),
    sa.Column('target_top_speed_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_objectives_aeroplane_id'), 'mission_objectives', ['aeroplane_id'], unique=True)
    op.create_index(op.f('ix_mission_objectives_id'), 'mission_objectives', ['id'], unique=False)
    op.create_table('weight_items',
    sa.Column('aeroplane_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('x_m', sa.Float(), nullable=False),
    sa.Column('y_m', sa.Float(), nullable=False),
    sa.Column('z_m', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_items_aeroplane_id'), 'weight_items', ['aeroplane_id'], unique=False)
    op.create_index(op.f('ix_weight_items_id'), 'weight_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_items_id'), table_name='weight_items')
    op.drop_index(op.f('ix_weight_items_aeroplane_id'), table_name='weight_items')
    op.drop_table('weight_items')
    op.drop_index(op.f('ix_mission_objectives_id'), table_name='mission_objectives')
    op.drop_index(op.f('ix_mission_objectives_aeroplane_id'), table_name='mission_objectives')
    op.drop_table('mission_objectives')
    # ### end Alembic commands ###
