"""add copilot_messages table

Revision ID: 705e8e49ef47
Revises: 5b41e8c65a14
Create Date: 2026-04-12 06:42:43.731805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705e8e49ef47'
down_revision: Union[str, None] = '5b41e8c65a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_messages',
    sa.Column('aeroplane_id', sa.Integer(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_aeroplane_id'), 'copilot_messages', ['aeroplane_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_id'), 'copilot_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_messages_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_aeroplane_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    # ### end Alembic commands ###
