"""added index to sort WingXSecs

Revision ID: 83493febb34a
Revises: a6a68bfaf421
Create Date: 2025-05-04 22:36:33.516748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83493febb34a'
down_revision: Union[str, None] = 'a6a68bfaf421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'wing_xsecs',
        sa.Column(
            'sort_index',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wing_xsecs', 'sort_index')
    # ### end Alembic commands ###
