"""renamed total_mass attribute to total_mass_kg

Revision ID: 93509b051fb3
Revises: 2f80f5c2b22f
Create Date: 2025-05-26 22:00:03.742549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93509b051fb3'
down_revision: Union[str, None] = '2f80f5c2b22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aeroplanes', sa.Column('total_mass_kg', sa.Float(), nullable=True))
    op.drop_column('aeroplanes', 'total_mass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aeroplanes', sa.Column('total_mass', sa.FLOAT(), nullable=True))
    op.drop_column('aeroplanes', 'total_mass_kg')
    # ### end Alembic commands ###
