"""add design_versions table

Revision ID: 93d974f885f1
Revises: 705e8e49ef47
Create Date: 2026-04-12 06:45:15.188611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d974f885f1'
down_revision: Union[str, None] = '705e8e49ef47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_versions',
    sa.Column('aeroplane_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_versions_aeroplane_id'), 'design_versions', ['aeroplane_id'], unique=False)
    op.create_index(op.f('ix_design_versions_id'), 'design_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_versions_id'), table_name='design_versions')
    op.drop_index(op.f('ix_design_versions_aeroplane_id'), table_name='design_versions')
    op.drop_table('design_versions')
    # ### end Alembic commands ###
