"""add components table

Revision ID: 94e41782f22d
Revises: 93d974f885f1
Create Date: 2026-04-12 06:47:42.840579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e41782f22d'
down_revision: Union[str, None] = '93d974f885f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mass_g', sa.Float(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_component_type'), 'components', ['component_type'], unique=False)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_component_type'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
