"""initial schema

Revision ID: a6a68bfaf421
Revises: 
Create Date: 2025-05-04 21:06:02.400617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.types import TypeDecorator, CHAR
import uuid

# revision identifiers, used by Alembic.
revision: str = 'a6a68bfaf421'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class GUID(TypeDecorator):
    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(UUID())
        return dialect.type_descriptor(CHAR(32))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        if dialect.name == 'postgresql':
            return str(value)
        if not isinstance(value, uuid.UUID):
            return "%.32x" % uuid.UUID(value).int
        return "%.32x" % value.int

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if not isinstance(value, uuid.UUID):
            value = uuid.UUID(value)
        return value


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeroplanes',
    sa.Column('uuid', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('xyz_ref', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_aeroplanes_id'), 'aeroplanes', ['id'], unique=False)
    op.create_table('fuselages',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aeroplane_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuselages_id'), 'fuselages', ['id'], unique=False)
    op.create_table('wings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symmetric', sa.Boolean(), nullable=True),
    sa.Column('aeroplane_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aeroplane_id'], ['aeroplanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wings_id'), 'wings', ['id'], unique=False)
    op.create_table('fuselage_xsecs',
    sa.Column('xyz', sa.JSON(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('n', sa.Float(), nullable=False),
    sa.Column('fuselage_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuselage_id'], ['fuselages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuselage_xsecs_id'), 'fuselage_xsecs', ['id'], unique=False)
    op.create_table('wing_xsecs',
    sa.Column('xyz_le', sa.JSON(), nullable=False),
    sa.Column('chord', sa.Float(), nullable=False),
    sa.Column('twist', sa.Float(), nullable=False),
    sa.Column('airfoil', sa.String(), nullable=False),
    sa.Column('wing_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wing_xsecs_id'), 'wing_xsecs', ['id'], unique=False)
    op.create_table('control_surfaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hinge_point', sa.Float(), nullable=True),
    sa.Column('symmetric', sa.Boolean(), nullable=True),
    sa.Column('deflection', sa.Float(), nullable=True),
    sa.Column('wing_xsec_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wing_xsec_id'], ['wing_xsecs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_surfaces_id'), 'control_surfaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_surfaces_id'), table_name='control_surfaces')
    op.drop_table('control_surfaces')
    op.drop_index(op.f('ix_wing_xsecs_id'), table_name='wing_xsecs')
    op.drop_table('wing_xsecs')
    op.drop_index(op.f('ix_fuselage_xsecs_id'), table_name='fuselage_xsecs')
    op.drop_table('fuselage_xsecs')
    op.drop_index(op.f('ix_wings_id'), table_name='wings')
    op.drop_table('wings')
    op.drop_index(op.f('ix_fuselages_id'), table_name='fuselages')
    op.drop_table('fuselages')
    op.drop_index(op.f('ix_aeroplanes_id'), table_name='aeroplanes')
    op.drop_table('aeroplanes')
    # ### end Alembic commands ###
