"""added fuselage xsection sort_index

Revision ID: df18c9f3ba1d
Revises: 1294198940a9
Create Date: 2025-06-20 10:46:30.179126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df18c9f3ba1d'
down_revision: Union[str, None] = '1294198940a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuselage_xsecs', sa.Column('sort_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuselage_xsecs', 'sort_index')
    # ### end Alembic commands ###
