#!/usr/bin/env python3
"""Build the AVL (Athena Vortex Lattice) binary from Fortran source.

Detects platform (macOS Homebrew vs Linux) and sets the correct X11 and
LAPACK/BLAS paths automatically. Produces the binary at exports/avl.

Usage:
    poetry run build-avl
    # or directly:
    python scripts/build_avl.py
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
AVL_DIR = PROJECT_ROOT / "Avl"
PLOTLIB_DIR = AVL_DIR / "plotlib"
EISPACK_DIR = AVL_DIR / "eispack"
BIN_DIR = AVL_DIR / "bin"
EXPORTS_DIR = PROJECT_ROOT / "exports"


def run(cmd: list[str], cwd: Path) -> None:
    print(f"  → {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        sys.exit(f"Build failed: {' '.join(cmd)}")


def detect_x11() -> tuple[str, str]:
    """Return (include_path, lib_path) for X11 on this platform."""
    if platform.system() == "Darwin":
        # Homebrew (arm64 or x86_64)
        brew_prefix = subprocess.run(
            ["brew", "--prefix"], capture_output=True, text=True
        ).stdout.strip()
        if brew_prefix and Path(f"{brew_prefix}/include/X11/Xlib.h").exists():
            return f"{brew_prefix}/include", f"{brew_prefix}/lib"
        # XQuartz fallback
        if Path("/opt/X11/include/X11/Xlib.h").exists():
            return "/opt/X11/include", "/opt/X11/lib"
    # Linux default
    if Path("/usr/include/X11/Xlib.h").exists():
        return "/usr/include", "/usr/lib/x86_64-linux-gnu"
    # Legacy path
    return "/usr/X11R6/include", "/usr/X11R6/lib"


def check_prerequisites() -> None:
    if not shutil.which("gfortran"):
        sys.exit(
            "gfortran not found. Install it:\n"
            "  macOS:  brew install gcc\n"
            "  Debian: apt install gfortran liblapack-dev libx11-dev"
        )
    if not shutil.which("make"):
        sys.exit("make not found. Install build tools for your platform.")


def write_plotlib_config(x11_include: str, x11_lib: str) -> None:
    """Write a config.make for plotlib with correct paths."""
    config = PLOTLIB_DIR / "config.make"
    config.write_text(f"""\
# Auto-generated by scripts/build_avl.py
PLTLIB = libPlt_gSP.a
DEFINE = -DUNDERSCORE
FC = gfortran
CC = cc
MARCH =
DP =
FFLAGS  = -O2 $(MARCH) $(DP)
CFLAGS  = -O2 $(MARCH) $(DEFINE) -I{x11_include}
CFLAGS0 = -O0 $(MARCH) $(DEFINE) -I{x11_include}
AR = ar r
RANLIB = ranlib
LINKLIB = -L{x11_lib} -lX11
WOBJ = Xwin2.o
WSRC = xwin11
""")


def build_plotlib() -> None:
    print("[1/3] Building plotlib...")
    # Clean previous objects
    for f in PLOTLIB_DIR.glob("*.o"):
        f.unlink()
    run(["make", "-f", "Makefile.all", "lib"], cwd=PLOTLIB_DIR)
    # Create symlink
    link = PLOTLIB_DIR / "libPlt.a"
    link.unlink(missing_ok=True)
    link.symlink_to("libPlt_gSP.a")


def build_eispack() -> None:
    print("[2/3] Building eispack...")
    for f in EISPACK_DIR.glob("*.o"):
        f.unlink()
    run(["make", "-f", "Makefile.mingw"], cwd=EISPACK_DIR)
    link = EISPACK_DIR / "libeispack.a"
    link.unlink(missing_ok=True)
    link.symlink_to("eispack_gSP.a")


def build_avl(x11_lib: str) -> None:
    print("[3/3] Building AVL...")
    for f in BIN_DIR.glob("*.o"):
        f.unlink()
    (BIN_DIR / "avl").unlink(missing_ok=True)

    # Override PLTLIB in makefile via environment/command line
    run(
        ["make", "-f", "Makefile.gfortran", f"PLTLIB=-L{x11_lib} -lX11", "avl"],
        cwd=BIN_DIR,
    )


def install() -> None:
    EXPORTS_DIR.mkdir(exist_ok=True)
    src = BIN_DIR / "avl"
    dst = EXPORTS_DIR / "avl"
    shutil.copy2(src, dst)
    dst.chmod(0o755)
    print(f"\n✓ AVL binary installed at: {dst}")


def main() -> None:
    print("Building AVL (Athena Vortex Lattice) from Fortran source\n")

    check_prerequisites()
    x11_include, x11_lib = detect_x11()
    print(f"  X11: include={x11_include} lib={x11_lib}\n")

    write_plotlib_config(x11_include, x11_lib)
    build_plotlib()
    build_eispack()
    build_avl(x11_lib)
    install()

    # Smoke test
    result = subprocess.run(
        [str(EXPORTS_DIR / "avl")],
        input="quit\n",
        capture_output=True,
        text=True,
        timeout=5,
    )
    if "Athena Vortex Lattice" in result.stdout:
        print("✓ Smoke test passed — AVL responds correctly")
    else:
        print("⚠ Smoke test: AVL ran but output unexpected", file=sys.stderr)


if __name__ == "__main__":
    main()
