FROM --platform=linux/amd64 ubuntu:22.04

COPY Avl /home/avl/

SHELL [ "/bin/bash", "-c" ]
WORKDIR /home/avl
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential gfortran liblapack-dev libblas-dev libx11-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cd plotlib && make gfortran && ln -s libPlt_gSP.a libPlt.a
RUN cd eispack && make -f Makefile.mingw && ln -s eispack_gSP.a libeispack.a
RUN cd bin && make -f Makefile.gfortran avl
